import os
import subprocess
import sys
from pathlib import Path
from autodoc_swarm.agent import create_swarm

def get_changed_files(target_dir: str):
    """
    Returns a list of files changed in the current PR or commit.
    Used for smart diffing to save LLM context window/costs.
    """
    event_name = os.environ.get("GITHUB_EVENT_NAME")
    doc_prefix = os.path.normpath(os.path.join(target_dir, "documentation")).replace("\\", "/") + "/"
    try:
        if event_name == "pull_request":
            base_ref = os.environ.get("GITHUB_BASE_REF")
            # Fetch the base branch to compare against
            subprocess.run(["git", "fetch", "origin", base_ref], check=True)
            result = subprocess.run(
                ["git", "diff", "--name-only", f"origin/{base_ref}"],
                capture_output=True, text=True, check=True
            )
        else:
            # On push, get changes in the latest commit
            result = subprocess.run(
                ["git", "diff", "--name-only", "HEAD~1", "HEAD"],
                capture_output=True, text=True, check=True
            )
        SKIP_SUFFIXES = {
            ".gitignore", ".dockerignore", ".npmignore", ".eslintignore",
            ".prettierignore", ".hgignore", ".bzrignore",
            ".gitattributes", ".editorconfig", ".gitmodules",
        }
        files = result.stdout.splitlines()
        return [
            f for f in files
            if f
            and not f.replace("\\", "/").startswith(doc_prefix)
            and Path(f).name not in SKIP_SUFFIXES
        ]
    except subprocess.CalledProcessError as e:
        print(f"Unable to determine changed files (possibly first commit). Proceeding with full scan. Detail: {e}")
        return []

def configure_git():
    subprocess.run(["git", "config", "--global", "user.name", "AutoDoc Swarm"], check=True)
    subprocess.run(["git", "config", "--global", "user.email", "autodoc-swarm@github.actions"], check=True)

    workspace = os.environ.get("GITHUB_WORKSPACE")
    if workspace:
        subprocess.run(["git", "config", "--global", "--add", "safe.directory", workspace], check=True)

def commit_and_push(target_dir):
    try:
        doc_dir = os.path.join(target_dir, "documentation/")
        if not os.path.exists(doc_dir):
            os.makedirs(doc_dir, exist_ok=True)
        subprocess.run(["git", "add", doc_dir], check=True)
        # Check if there are changes to commit
        status = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
        if not status.stdout.strip():
            print("No documentation changes to commit.")
            return False

        subprocess.run(["git", "commit", "-m", "docs: auto-generated by Swarm Queen"], check=True)

        # Use head ref on PRs, ref name on pushes
        event_name = os.environ.get("GITHUB_EVENT_NAME")
        branch = os.environ.get("GITHUB_HEAD_REF") if event_name == "pull_request" else os.environ.get("GITHUB_REF_NAME")
        token = os.environ.get("GITHUB_TOKEN")
        repo = os.environ.get("GITHUB_REPOSITORY")

        if not token:
            print("ERROR: GITHUB_TOKEN is not set. Cannot push.")
            sys.exit(1)
        if not repo:
            print("ERROR: GITHUB_REPOSITORY is not set. Cannot push.")
            sys.exit(1)
        if not branch:
            print("ERROR: Could not determine target branch. Cannot push.")
            sys.exit(1)

        print(f"Pushing documentation to {branch}...")
        remote_url = f"https://x-access-token:{token}@github.com/{repo}.git"
        subprocess.run(["git", "push", remote_url, f"HEAD:{branch}"], check=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Git operations failed: {e}")
        sys.exit(1)

def write_step_summary(content: str):
    summary_file = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_file:
        with open(summary_file, "a") as f:
            f.write(content + "\n")

def main():
    print("Starting AutoDoc Agent Swarm Github Action...")

    provider = os.environ.get("INPUT_PROVIDER", "openrouter")
    queen_model = os.environ.get("INPUT_QUEEN_MODEL", "anthropic/claude-3.5-sonnet")
    worker_model = os.environ.get("INPUT_WORKER_MODEL", "anthropic/claude-3.5-sonnet")
    drone_model = os.environ.get("INPUT_DRONE_MODEL", "anthropic/claude-3.5-sonnet")
    target_dir = os.environ.get("INPUT_TARGET_DIR", ".")

    api_key = os.environ.get("API_KEY")
    if not api_key:
        print("ERROR: api_key input is required.")
        sys.exit(1)

    # Map the generic API_KEY to the specific provider ENV var so llm_setup.py can find it
    provider_upper = provider.upper()
    os.environ[f"{provider_upper}_API_KEY"] = api_key

    # Change to github workspace
    workspace = os.environ.get("GITHUB_WORKSPACE")
    if workspace:
        os.chdir(workspace)
        print(f"Working in workspace: {workspace}")

    configure_git()

    changed_files = get_changed_files(target_dir)
    if changed_files:
        print(f"Smart Diffing identified {len(changed_files)} changed files.")
        files_str = ", ".join(changed_files)
        kickoff_msg = f"Begin documentation process. Prioritize documenting these specifically modified files: {files_str}. Ensure strict adherence to your directives."
    else:
        print("No files changed or unable to determine changes. Proceeding with full scan.")
        kickoff_msg = "Begin a deep scan of the repository. Evaluate freshness of files and document all code files found according to your directives. Stop when all tasks are complete."

    try:
        queen = create_swarm(
            target_dir=target_dir,
            provider=provider,
            queen_model=queen_model,
            worker_model=worker_model,
            drone_model=drone_model
        )

        response = queen.invoke({"messages": [("user", kickoff_msg)]})
        try:
            if isinstance(response, dict) and response.get("messages"):
                final_output = response["messages"][-1].content
            else:
                final_output = str(response)
        except Exception:
            final_output = str(response)
        print("--- Final Queen Output ---")
        print(final_output)

        # Write summary
        write_step_summary(f"## AutoDoc Swarm Execution Complete 🐝\n\n**Models Used:**\n- Queen: `{queen_model}`\n- Worker: `{worker_model}`\n- Drone: `{drone_model}`\n\n**Queen Output:**\n```\n{final_output}\n```")

        success = commit_and_push(target_dir)
        if success:
            write_step_summary("✅ Successfully generated and pushed documentation updates.")
        else:
            write_step_summary("ℹ️ No new documentation changes required.")

    except Exception as e:
        print(f"Error executing swarm: {e}")
        write_step_summary(f"❌ **Error executing swarm:**\n```python\n{e}\n```")
        sys.exit(1)

if __name__ == "__main__":
    main()
